version: '3.3'
services:
  TR:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '1289:3306'
    volumes:
      - my-db:/var/lib          /mysql
  adminer:
    image: dockette/adminer:full-php5
    ports:
      - '6464:8080'
volumes:
  my-db: