server:
  port: 7834
spring:
  datasource:
    url: jdbc:mysql://localhost:1289/TR?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: true
